# languages.py
TEXTS = {
    'ar': {
        'welcome': "أهلاً بك في المتجر الرقمي.\nاختر ما يناسبك من القائمة أدناه:",
        'menu_products': "🛒 المنتجات",
        'menu_account': "👤 حسابي",
        'menu_deposit': "💳 شحن الرصيد",
        'menu_lang': "🌐 اللغة / Language",
        'menu_support': "🎧 خدمة العملاء",
        'back': "🔙 رجوع",
        'account_info': "👤 بيانات حسابك الشخصي:\n\n🆔 الآيدي: `{user_id}`\n🔑 الباسورد: `{password}`\n💰 الرصيد الحالي: **{balance} USDT**",
        'deposit_info': "💳 طريقة شحن الرصيد بـ USDT (شبكة TRC20 - بايننس / بايبت):\n\nقم بالتحويل إلى العنوان التالي:\n`{address}`\n\nبعد التحويل، أرسل رقم العملية (TxID) أو الإيصال للدعم.",
        'choose_product': "🛒 اختر المنتج الذي ترغب في شرائه:",
        'buy_btn': "✅ شراء الآن",
        'insufficient_balance': "❌ رصيدك الحالي غير كافي لإتمام الشراء.",
        'purchase_success': "🎉 تمت عملية الشراء بنجاح!\n\n📦 المنتج: {name}\n💰 المبلغ المخصوم: {price}$\n💵 المتبقي في رصيدك: **{balance} USDT**\n\n🔑 تفاصيل المنتج:\n`{details}`",
        'lang_changed': "✅ تم تغيير اللغة بنجاح إلى العربية.",
        'admin_btn': "⚙️ لوحة التحكم (الأونر)",
        'add_prod_btn': "➕ إضافة منتج جديد",
        'admin_panel_text': "⚙️ لوحة تحكم الأونر:\n\nاختر الإجراء المطلوب أو استخدم أمر شحن الرصيد للمستخدمين:\n`/addbalance user_id amount`",
        'ask_name_ar': "أدخل اسم المنتج باللغة العربية:",
        'ask_name_en': "أدخل اسم المنتج باللغة الإنجليزية:",
        'ask_name_ru': "أدخل اسم المنتج باللغة الروسية:",
        'ask_price': "أدخل سعر المنتج بالدولار (USDT) (مثال: 15.5):",
        'ask_details_ar': "أدخل تفاصيل ومحتوى المنتج باللغة العربية:",
        'ask_details_en': "أدخل تفاصيل ومحتوى المنتج باللغة الإنجليزية:",
        'ask_details_ru': "أدخل تفاصيل ومحتوى المنتج باللغة الروسية:",
        'product_added_success': "✅ تمت إضافة المنتج بنجاح إلى المتجر وتفعيله فوراً!"
    },
    'en': {
        'welcome': "Welcome to the digital store.\nChoose an option from the menu below:",
        'menu_products': "🛒 Products",
        'menu_account': "👤 My Account",
        'menu_deposit': "💳 Deposit",
        'menu_lang': "🌐 Language",
        'menu_support': "🎧 Support",
        'back': "🔙 Back",
        'account_info': "👤 Your Account Details:\n\n🆔 ID: `{user_id}`\n🔑 Password: `{password}`\n💰 Current Balance: **{balance} USDT**",
        'deposit_info': "💳 How to deposit USDT (TRC20 - Binance / Bybit):\n\nTransfer to the following address:\n`{address}`\n\nAfter transferring, send the TxID or receipt to support.",
        'choose_product': "🛒 Choose the product you want to buy:",
        'buy_btn': "✅ Buy Now",
        'insufficient_balance': "❌ Your current balance is insufficient.",
        'purchase_success': "🎉 Purchase successful!\n\n📦 Product: {name}\n💰 Deducted: {price}$\n💵 Remaining Balance: **{balance} USDT**\n\n🔑 Product Details:\n`{details}`",
        'lang_changed': "✅ Language successfully changed to English.",
        'admin_btn': "⚙️ Owner Control Panel",
        'add_prod_btn': "➕ Add New Product",
        'admin_panel_text': "⚙️ Owner Control Panel:\n\nChoose an action or use balance command:\n`/addbalance user_id amount`",
        'ask_name_ar': "Enter product name in Arabic:",
        'ask_name_en': "Enter product name in English:",
        'ask_name_ru': "Enter product name in Russian:",
        'ask_price': "Enter product price in USDT (e.g. 15.5):",
        'ask_details_ar': "Enter product details in Arabic:",
        'ask_details_en': "Enter product details in English:",
        'ask_details_ru': "Enter product details in Russian:",
        'product_added_success': "✅ Product successfully added to the store!"
    },
    'ru': {
        'welcome': "Добро пожаловать в цифровой магазин.\nВыберите вариант из меню ниже:",
        'menu_products': "🛒 Продукты",
        'menu_account': "👤 Мой аккаунт",
        'menu_deposit': "💳 Пополнить",
        'menu_lang': "🌐 Язык",
        'menu_support': "🎧 Поддержка",
        'back': "🔙 Назад",
        'account_info': "👤 Данные вашего аккаунта:\n\n🆔 ID: `{user_id}`\n🔑 Пароль: `{password}`\n💰 Текущий баланс: **{balance} USDT**",
        'deposit_info': "💳 Как пополнить USDT (TRC20 - Binance / Bybit):\n\nПереведите на следующий адрес:\n`{address}`\n\nПосле перевода отправьте TxID или чек в поддержку.",
        'choose_product': "🛒 Выберите продукт, который хотите купить:",
        'buy_btn': "✅ Купить сейчас",
        'insufficient_balance': "❌ Недостаточно средств на балансе.",
        'purchase_success': "🎉 Покупка успешно завершена!\n\n📦 Продукт: {name}\n💰 Списано: {price}$\n💵 Остаток: **{balance} USDT**\n\n🔑 Детали продукта:\n`{details}`",
        'lang_changed': "✅ Язык успешно изменен на русский.",
        'admin_btn': "⚙️ Панель управления",
        'add_prod_btn': "➕ Добавить продукт",
        'admin_panel_text': "⚙️ Панель управления:\n\nВыберите действие или используйте команду:\n`/addbalance user_id amount`",
        'ask_name_ar': "Введите название на арабском:",
        'ask_name_en': "Введите название на английском:",
        'ask_name_ru': "Введите название на русском:",
        'ask_price': "Введите цену в USDT (например, 15.5):",
        'ask_details_ar': "Введите детали на арабском:",
        'ask_details_en': "Введите детали на английском:",
        'ask_details_ru': "Введите детали на русском:",
        'product_added_success': "✅ Продукт успешно добавлен в магазин!"
    }
}
